name: Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          check-latest: true
          cache: false

      - name: Build Module
        run: make module
        shell: bash

      - name: Load Module
        run: sudo make load
        shell: bash

      - name: Generate Test Data
        run: make test-generate
        shell: bash

      - name: Set 'vm.max_map_count' parameter
        run: sudo sysctl -w vm.max_map_count=262144
        shell: bash

      - name: Run Kernel Module Test
        run: make test
        shell: bash

      - name: Unload Module
        run: sudo make unload
        shell: bash

      - name: Run Userspace Test
        run: make test-userspace
        shell: bash

      - name: Build Module with Benchmarking
        run: BENCHMARK=true make module
        shell: bash

      - name: Load Module
        run: sudo make load
        shell: bash

      - name: Run Kernel Module Test (With Benchmarking)
        run: make test
        shell: bash

      - name: Print last 30 dmesg logs
        run: sudo dmesg | tail -n 30
        shell: bash

      - name: Unload Module
        run: sudo make unload
        shell: bash

      - name: Cleanup Module
        run: make clean
        shell: bash