name: Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          check-latest: true
          cache: true

      - name: Build Module
        run: make module
        shell: bash

      - name: Load Module
        run: make load
        shell: bash

      - name: Run Test
        run: make test
        shell: bash

      - name: Unload Module
        run: make unload
        shell: bash

      - name: Cleanup Module
        run: make clean
        shell: bash